tests/plugins/test_reporting_consistency.py
troubadix/plugins/__init__.py
troubadix/plugins/reporting_consistency.py

**What**: Check-reporting-consistency plugin from https://gitlab.greenbone.net/production/gsf-qa/-/blob/master/nvt-qa-scripts/steps/58-check-reporting-consistency.py
This is a version without the openvas generated SQLite database as previously requested.
It really looks similar to check_security_messages, check_cve_format and check_cve_format!
Since I don't really know NASL scripting, i recommend generating this DB at the moment we have a pre-plugin loader in the linter.
Maybe there are steps in DB creation where "cvss_base tags" be merged from various .nasl .inc files for an OID or something else.
**Why**:
DEVOPS-128
**How**:
**Checklist**:

Add: `ReportingConsistency` Plugin

---

troubadix/argparser.py
troubadix/plugins/__init__.py

**What**:
In the console output only the plugin names not the plugin class names
are displayed. Therefore a user should be allowed to use this name for
excluding and including plugins in a run.
**Why**:
**How**:
**Checklist**:

Allow for using plugin name in include and exclude args

---

tests/test_argparser.py
tests/test_runner.py
troubadix/argparser.py
troubadix/plugins/__init__.py
troubadix/runner.py
troubadix/troubadix.py

**What**:
* Detach the Plugin `UpdateModificationDate`
* This plugin is only used to update the modification date and script version, not for general Linting/QA, thus it should not run on default
* Run this plugin with `--update-date` parameter   
**Why**:
**How**:
**Checklist**:

Change: Add argument `--update-date` to run Plugin `UpdateModificationDate`

---

tests/plugins/test_todo_tbd.py
troubadix/plugins/todo_tbd.py

**What**:
changed CheckTodoTbd to return Warning instead of Error
**Why**:
**How**:
- Return LinterWarning instead of of LinterError.
- Changed tests to check for instance of LinterWarning
**Checklist**:

Change: changed CheckTodoTbd to return Warning instead of Error

---

troubadix/plugins/dependencies.py

They are gone from the VTs structure (all files got moved into the /attic) folder so the checks can be removed now.

Change: Remove no longer existing directories from dependencies.py

---

tests/plugins/test_duplicated_script_tags.py
troubadix/plugins/duplicated_script_tags.py

**What**:
Exclude tag  script_add_preference from plugin CheckDuplicatedScriptTags.
**Why**:
Tag is actually allowed to occur multiple times.
**How**:
**Checklist**:

Change: excluded ADD_PREFERENCE pattern from duplcated script check

---

troubadix/plugins/valid_oid.py

**What**:
- fixed oid-scheme for firefox
- updated oid-range
**Why**:
- https://jira.greenbone.net/browse/DEVOPS-185
- https://jira.greenbone.net/browse/DEVOPS-186
**How**:
Executed plugin on current state of https://github.com/greenbone/vulnerability-tests 
**Checklist**:

Change: updated oid range and fixed firefox check

---

troubadix/argparser.py
troubadix/troubadix.py

**What**:
Always pass arguments to the parse_args function.
**Why**:
**How**:
**Checklist**:

Fix: Ensure parsing arguments for troubadix

---

tests/plugins/test_http_links_in_tags.py
troubadix/plugins/http_links_in_tags.py

**What**:
Reworked check_to_continue method to be easier to maintain by creating a simple list of text phrases to exclude.
**Why**:
It is easier to maintain and add new entries
**How**:
Passes the existing unittests
**Checklist**:

Plugin http_links_in_tags overhauled check_to_continue method

---

tests/plugins/test_http_links_in_tags.py
troubadix/plugins/http_links_in_tags.py

**What**:
Added recent exclusions to the exclusion list
**Why**:
To keep parity between the old QA and troubadix.
MR 11193 in VTS repo
**How**:
Added new testcases and confirmed they ran successfully
**Checklist**:

Add: New exclusions for `http_links_in_tags`

---

troubadix/codespell/codespell.exclude

**What**:
Added 2 new excludes to codespell
**Why**:
To keep parity between old QA codespell and troubadix
**Checklist**:

Added 2 more excludes for Notus Slackware launch

---

tests/plugins/test_duplicated_oid.py
tests/plugins/test_no_solution.py
troubadix/plugin.py
troubadix/runner.py

**What**:
Drop the LinterMessage and change LinterResult into the base class.
**Why**:
LinterMessage was more or less unused and therefore unnecessary.
**How**:
**Checklist**:

Change: Cleanup linter reporting classes

---

troubadix/codespell/codespell.exclude

**What**:
Recent additions and fixes to codespell.exclude
**Why**:
To keep parity between old QA and troubadix

New and fixed entries to codespell.exclude

---

troubadix/plugins/script_family.py

**What**:
Added the script family for Rocky Linux LSCs to the `script_family` check.
**Why**:
The `script_family` is new and would otherwise fail the QA check.
Also to maintain parity between troubadix and old QA
**Checklist**:

Script family check Rocky Linux addition

---

troubadix/plugins/script_version_and_last_modification_tags.py

**What**:
.inc files don't have these tags so checking them would cause false positives like seen here:
```
$ troubadix --files nasl/common/bad_ssh_host_keys.inc
ℹ Time elapsed: 0:00:00.274571
× check_script_version_and_last_modification_tags         2        0
⚠ check_spelling                                          0        1
ℹ sum                                                     1        2
```
**Why**:
N/A
**How**:
N/A
**Checklist**:

Change: Don't run script_version()/last_modification plugin against .inc files

---

tests/plugins/test_spelling.py
troubadix/plugins/spelling.py

**What**:
- In the "old" QA step the .inc file was excluded via the `--skip` parameter of codespell, this seems to have been missed during the migration to Troubadix
- A spelling mistake should throw an error to fail the QA
**Why**:
N/A
**How**:
N/A
**Checklist**:

Change: Report spelling problems as Error. Exclude one .inc file.

---

troubadix/plugins/valid_oid.py

**What**:
Running the plugin shows the following previously:
```
$ troubadix --include-tests check_valid_oid --file nasl/common/gsf/2018/vmware/gb_vmware_fusion_vmxnet3_stack_memory_usage_vuln_macosx.nasl -v
/path/to/nasl/common/gsf/2018/vmware/gb_vmware_fusion_vmxnet3_stack_memory_usage_vuln_macosx.nasl
ℹ Checking gsf/2018/vmware/gb_vmware_fusion_vmxnet3_stack_memory_usage_vuln_macosx.nasl (1/1)
ℹ     Results for plugin check_valid_oid
×         script_oid() is using an invalid OID '1.3.6.1.4.1.25623.1.0.8141330' (unassigned OID range)
ℹ Time elapsed: 0:00:00.015437
× check_valid_oid                                         1 …
```

Fix: Exclusion in valid_oid.py

---

tests/plugins/test_valid_oid.py
troubadix/plugins/valid_oid.py

**What**:
- This was implemented quite sub-optimal in the old Feed-QA in the past but got improved within it in the meantime. Applying the same changes / improvements to Troubadix as well
- Also dropped one invalid comment about some badword checks
- One test for an "unknown" vendor has been changed from 14 (which is now Rocky Linux) to 99 so that we don't need to change that one after every addition of a new Linux distro
**Why**:
Easier maintenance of additions to this code.
**How**:
```
$ troubadix --include-tests check_valid_oid -f
```
**Checklist**:

Change: Simplify valid_oid.py plugin. Drop invalid comment.

---

troubadix/reporter.py

**What**:
Looked like this:
```
× check_no_solution                                     240       27
ℹ sum                                                    27      240
```
Now will look like this:
```
× check_no_solution                                     240       27
ℹ sum                                                   240       27
```
**Why**:
**How**:
**Checklist**:

Fix: Mixed up error and warning sums

---

tests/test_runner.py
troubadix/plugins/__init__.py
troubadix/runner.py

**What**:
* The Prerun Plugins could not be in or excluded and ran every time troubadix has been executed, this is changed now.
**Why**:
DEVOPS-237
**How**:
**Checklist**:

Change: Make prerun Plugins in- and excludable

---

tests/plugins/test_no_solution.py
troubadix/plugins/no_solution.py

**What**:
* NoSolution will now print the file names
* removed some false positives:
* the design of `parse_date` substituted the `st` in any `August` dates
* I also found solutions that had abbreviation of month  (`Oct`), thus I added a date format with `%b`.
**Why**:
DEVOPS-235
**How**:
**Checklist**:

Fix: Plugin `NoSolution` prints filename of findings

---

tests/plugins/test_duplicated_script_tags.py
troubadix/plugins/duplicated_script_tags.py

**What**:Add allow list for duplicated script_dependencies
**Why**:
Note that we shouldn't generally allow script_dependencies() multiple times (because this might be an error due to copy'n'paste or similar) but only for the existing exclusions AND the three VTs mentioned above (because they are some kind of a special case which is allowed for now because we know that the tag isn't used wrongly).
**How**:
**Checklist**:

Add allow list for duplicated script_dependencies

---

troubadix/plugins/prod_svc_detect_in_vulnvt.py

**What**:
As noticed in VTD-1540 the plugin had checked .inc files but this check is only valid for .nasl files.
**Why**:
Avoid false positives.
**How**:
N/A
**Checklist**:

Fix: Don't check .inc in prod_svc_detect_in_vulnvt.py to fix false positives.

---

tests/test_helper.py
troubadix/helper/helper.py

**What**:
When checking files of different folders, troubadix breaks
**Why**:
**How**:
* don't look for the subfolder (e.g. `common, 2010`) but for the folder `nasl` only ...
**Checklist**:

Fix: Calculating path root in case of files in multiple directories

---

troubadix/plugins/spelling.py

**What**:
Some of the VTs got deprecated recently and moved from e.g. `gsf/PCIDSS/PCIDSS_something.nasl` to `gsf/attic/PCIDSS_something.nasl` so the previous exclusion didn't worked anymore. Updated it now accordingly.
**Why**:
N/A
**How**:
N/A
**Checklist**:

Change: Update exclusion pattern in spelling.py

---

troubadix/plugins/risk_factor.py

**What**:
All plugin names have included the `check_` prefix expect this one like seen here:
```
✓     No results for plugin check_reporting_consistency
✓     No results for plugin risk_factor
✓     No results for plugin check_script_category
✓     No results for plugin check_script_copyright
✓     No results for plugin check_script_family
```
**Why**:
Consistency reasons
**How**:
N/A
**Checklist**:

Change: Update plugin name of risk_factor.py

---

tests/plugins/test_copyright_text.py
tests/plugins/test_script_copyright.py
troubadix/plugins/copyright_text.py
troubadix/plugins/script_copyright.py

**What**:
Replaced #272 as a feature branch.
While migrating/porting the "old" `check_copyright_text.py` to Troubadix it seems that it was tried to split the two checks in that step into two separate plugins but it was missed to remove the check from one plugin which had been covered in the other one causing duplicated results to be reported.
This PR should fix that by removing the check from the plugins which had been covered by the other plugin.
Notes:
- I have also added a few additional cases for one plugin test.
- I haven't put any additional work into the text output of `script_copyright.py` (Because e.g. it also reports if the `script_copyright()` is completely missing but this is currently not reflected in the output) because this tag will be deprecated and removed completely in …

Fix: Duplicated checks in copyright_text and script_copyright

---

tests/plugins/test_copyright_text.py
troubadix/plugins/copyright_text.py

**What**:
1. If the is doing plugin reports the VT `is using` and not `was using` the incorrect copyright statement
2. If the plugin is doing the "fix" then there is a separate string noticing that the copyright statement has been update so the `was using` is IMHO still not required
3. The missing `statement` word was added for consistency reasons
Instead of `is using` we could also say `is/was using` but IMHO this is too much for such a minor thing.
**Why**:
Consistency reasons.
**How**:
N/A
**Checklist**:

Change: Minor textual change in copyright_text.py plugin.

---

troubadix/plugins/reporting_consistency.py

**What**:
Those are files which are correctly using a log_message() to do e.g. some additional reporting for the user. This is a valid case which doesn't need to be changed.
Part of:
- VTD-1541
- VTD-1534
**Why**:
Avoid reporting of errors for files / .nasl scripts which are valid.
**How**:
N/A
**Checklist**:

Change: Exclude valid .nasl scripts in reporting_consistency.py

---

troubadix/plugins/reporting_consistency.py

**What**:
The example and template files shouldn't be checked at all because the plugin would throw an unecessary error for them if e.g. not running from within the nasl/common folder. But all three files are just examples and don't need to be checked at all.
- Closes: DEVOPS-277
- Related to: VTD-1541
**Why**:
Avoid unnecessary reporting for errors which are no real errors.
**How**:
Ran the following before / after this PR from within the main root dir of the vulnerability-tests repo (not from within `nasl/common`) to see that the reporting is now gone:
```
$ troubadix -f --include-tests check_reporting_consistency -v
```
**Checklist**:

Change: Exclude example and template files in reporting_consistency.py

---

troubadix/standalone_plugins/changed_oid.py

**What**:
Before this PR the output looked like:
```
Check file nasl/common/sw_http_os_detection.nasl
Change OID IN nasl/common/sw_http_os_detection.nasl OID_NEW: 1.3.6.1.4.1.25623.1.0.111068 OID OLD: 1.3.6.1.4.1.25623.1.0.111067
```
which was now changed to the following:
```
OID of VT nasl/common/sw_http_os_detection.nasl was changed. This is only allowed in rare cases (e.g. a duplicate OID got fixed or a single VT was split into two VTs).
OID NEW: 1.3.6.1.4.1.25623.1.0.111068
OID OLD: 1.3.6.1.4.1.25623.1.0.111067
```
**Why**:
To stay a little bit closer to the output of the "old" step and to give more background info on this problem.
There was also a inconsistency in the output because in one part `OID_NEW` (with an underscore) was used while the other part had `OID OLD` (without an …

Change: Update text with more info in changed_oid.py plugin

---

troubadix/plugins/__init__.py

**What**:
Short follow up to #288 because the `deprecated_functions.py` still wasn't enabled yet.
I have also re-sorted the list of imports based on `ls -1 *.py | grep -v "__init__"`, the `PLUGINS` list also got re-sorted.
There is also a special thing about `PLUGINS`, AFAICT it is expected that it doesn't include the function name from `update_modification_date.py` because this seems to be a separate mode `--update-dates` which shouldn't be running as a plugin.
**Why**:
DEVOPS-284
**How**:
N/A
**Checklist**:

Fix: Enable missing deprecated_funcions plugin. Re-sort some lists.

---

troubadix/argparser.py

**What**:
Previously the output of `--help` looked like the following:
```
Define number of jobs, that should run simultaneouslyDefault: 2
```
This should be now the following instead:
```
Define number of jobs, that should run simultaneously. Default: 2
```
**Why**:
N/A
**How**:
N/A
**Checklist**:

Fix: Add missing space and full stop to help output.

---

troubadix/helper/patterns.py

**What**:
Fix: re.DOTALL is needed to get multiline tag values
**Why**:
Multiline tag values are needed by check_double_end_points
> In the default mode, `.` matches any character except a newline. If the [DOTALL](https://docs.python.org/3/library/re.html#re.DOTALL) flag has been specified, this matches any character including a newline.
**How**:
**Checklist**:

Fix: re.DOTALL is needed to get multiline tag values

---

troubadix/plugins/script_calls_recommended.py

**What**:Fix misspelled required_ports to require_ports in script_calls_recommended.py.
**Why**:
**How**:
**Checklist**:

Fix: misspelled required_ports to require_ports

---

troubadix/plugins/double_end_points.py

**What**:
The "old" step had a `'.*\.\s*\."\s*\)\s*;'` regex while the new / migrated plugin one had `'\.\s*\.(?P<quote>[\'"])\s*\)\s*;'`. Due to the first missing `.*` the string returned in `doubled_end_points_match.group(0)` only included the following:
```
..");
```
while it actually should contain the following so that the existing exclusion is working:
```
like displaying BLOB-data as image or download-link and much more...");
```
This PR fixes this problem by adding the additional `.*` to make the exclusion working again.
**Why**:
Reduce false positives found in the scope of VTD-1621
**How**:
Run the following before this PR:
```
troubadix --include-tests check_double_end_points -d nasl/common
```
which showed 16 errors:
```
Plugin                                             Errors …
```

Fix: Not working exclusion in double_end_points.py

---

tests/plugins/test_last_modification.py
tests/test_runner.py
troubadix/plugins/__init__.py
troubadix/plugins/last_modification.py

**What**:
Run checking the last modification date and script version as a standard
plugin. This will allow to abandon the `--update-date` argument and
replace it with `--include-tests check_last_modification --fix`.
**Why**:
Remove the hacked `--update-date` mechanism from troubadix at the end.
**How**:
**Checklist**:

Change: Rework UpdateModificationDate into a "normal" plugin

---

troubadix/plugins/last_modification.py

**What**:
With #304 the plugin got reworked to always run by default. But as `.inc` files don't have such a `last_modification` date this change causes false positives / errors against such `.inc` files.
**Why**:
Fix false positives
**How**:
Run e.g. the following below. Before this PR Troubadix reported a false positive which should be gone afterwards.
```
$ troubadix --files nasl/common/ssl_funcs.inc -v
ℹ Checking common/ssl_funcs.inc (1/1)
ℹ     Results for plugin check_last_modification
×         VT does not contain a modification day script tag.
ℹ     Results for plugin check_todo_tbd
⚠         VT contains #TODO/TBD/@todo keywords.
⚠         VT contains #TODO/TBD/@todo keywords.
⚠         VT contains #TODO/TBD/@todo keywords.
⚠         VT contains …
```

Fix: Don't run last_modification.py against .inc files.

---

tests/plugins/test_script_calls_empty_values.py
troubadix/plugins/script_calls_empty_values.py

**What**:
Special script tag name can not be a regex in script_calls_empty_values. This leads to regex mismatches. Further only check script_tag and script_xref in script_calls_empty_values.
**Why**:
- DEVOPS-291
- DEVOPS-286
**How**:
**Checklist**:

Fix: Special script tag name can not be a regex in script_calls_empty_values

---

tests/plugins/test_last_modification.py
tests/plugins/test_script_version_and_last_modification_tags.py
tests/test_runner.py
troubadix/plugins/last_modification.py
troubadix/plugins/script_version_and_last_modification_tags.py

**What**:
Move responsibility for checking script_version and last_modification tag into the `check_script_version_and_last_modification_tags` plugin.
The `--fix` functionality for `check_script_version_and_last_modification_tags` is slightly different from `check_last_modification`. It only updates the script version and last modification date if the format is wrong. Currently `check_last_modification` updates both unconditionally. This behavior of `check_last_modification` has been kept for the [feed deployment](https://github.com/greenbone/vulnerability-tests/blob/main/.github/workflows/feed-deployment.yml#L257) until there is a replacement.
[DEVOPS-297](https://jira.greenbone.net/browse/DEVOPS-297)
**Why**:
Currently script_version and last_modification are checked twice in …

Update last modification plugins

---

pyproject.toml
tests/standalone_plugins/__init__.py
tests/standalone_plugins/test_last_modification.py
troubadix/helper/patterns.py
troubadix/plugins/script_version_and_last_modification_tags.py
troubadix/standalone_plugins/last_modification.py

**What**:
This new console line interface tool allows to update the script_version
and last_modification tag to the current date and time for passed nasl
scripts. It will replace the deprecated `check_last_modification`
plugin.
**Why**:
Allow to unconditionally update `last_modification` date for nasl scripts.
**How**:
**Checklist**:

Change: Add a standalone plugin/tool for updating last modification

---

.github/CODEOWNERS

**What**:
Adds @n-thumann and @mbrinkhoff to the codeowners file to enable normal reviews.
**Why**:
Part of the handover process
**How**:
**Checklist**:

Added nthumann and mbrinkhoff to codeowners file

---

tests/plugins/test_http_links_in_tags.py
troubadix/plugins/http_links_in_tags.py

**What**:
This PR adds a exclude to http_links_in_tags plugin.
**Why**:
To make the QA of https://github.com/greenbone/vulnerability-tests/pull/78 happy.
**How**:
**Checklist**:

Add exclusion to http_links_in_tags plugin

---

troubadix/helper/patterns.py
troubadix/plugins/duplicate_oid.py

**What**:
Remove any special handling of `script_id()` from Troubadix.
The `script_id()` itself is gone since quite some years with greenbone/openvas-scanner#54 and running a VT using it yields the following:
```
lib  nasl-Message: 08:24:56.287: [10679](oid.nasl:1) Undefined function 'script_id'
Error while processing oid.nasl.
1 scripts with one or more errors found
```
Furthermore `script_id()` is also already included in the `deprecated_functions.py` plugin and would be also reported by that if used.
**Why**:
Remove not required code.
**How**:
N/A
**Checklist**:

Remove: Handling of unsupported script_id() tag.

---

tests/plugins/test_http_links_in_tags.py
troubadix/plugins/http_links_in_tags.py

**What**:
Similar to #322 but for the `https://` scheme.
**Why**:
Sooner or later there will be a similar false positive like solved in #322 
**How**:
N/A
**Checklist**:

Add: Exclusion to http_links_in_tags plugin

---

tests/plugins/test_script_calls_recommended.py
troubadix/plugins/script_calls_recommended.py

**What**:
Fixed `script_calls_recommended.py` so that `script_dependencies` can recognize multiline values.
**Why**:
We had false-positives with the plugin.
Jira: VTD-1626
**How**:
https://stackoverflow.com/questions/33312175/matching-any-character-including-newlines-in-a-python-regex-subexpression-not-g
**Checklist**:

Fix: Script dependencies allow multiline value

---

tests/plugins/test_grammar.py
troubadix/plugins/grammar.py

**What**:
Extend the regex to catch additional common grammar problems / mistakes.
**Why**:
N/A
**How**:
- Run `troubadix -d nasl/common --include-tests check_grammar -v` (Should find 17 occurrences on a VT repository before greenbone/vulnerability-tests#347)
- :robot:
**Checklist**:

Add: Additional grammar regex and related tests for grammar.py

---

tests/standalone_plugins/test_changed_oid.py
troubadix/standalone_plugins/changed_oid.py

**What**:
As discussed in #327 remove these things to avoid confusion or other problems in the future.
**Why**:
From https://github.com/greenbone/troubadix/pull/327#issuecomment-1191200425:
> yes. running python scripts directly should be avoided.
> 
> And just for your info, the encoding line isn't necessary at all anymore since Python 3 where utf-8 is always used. It is only necessary for Python 2.
**How**:
N/A
**Checklist**:

Remove: Executable bit and/or shebang and coding string in changed_oid files

---

troubadix/plugins/spelling.py

**What**:
This is now also happening in MGASA/Mageia related advisories like seen in greenbone/vulnerability-tests#385:
```
ℹ Checking 21.04/2022/mageia/mgasa-2022-0263.nasl (6/7)
ℹ     Results for plugin check_spelling
×         /path/to/2022/mageia/mgasa-2022-0263.nasl:93: conexant ==> connexant
```
**Why**:
Exclude false positives
**How**:
N/A
**Checklist**:

Change: Update spelling exclusion for LSCs in spelling.py

---

tests/plugins/__init__.py
tests/plugins/test_spelling.py
troubadix/plugins/__init__.py
troubadix/plugins/spelling.py

**What**:
Switched spelling plugin to be `FilesPlugin` based because the `FilePlugin` based approach was too slow
Closes: Jira VTD-1656
**Why**:
`FilePlugin` approach took upwards of 2 hours to finish a full run.
Current runtime (local) is about 4 minutes
**How**:
Tests have been adjusted accordingly.
**Checklist**:

Switch spelling plugin to files plugin

---

tests/standalone_plugins/test_version_updated.py
troubadix/standalone_plugins/version_updated.py

**What**:
Inverted the if statement in main to produce the expected exit code.
**Why**:
The check was inverted and would return 2 for success and 0 for error, this would break the QA workflow.
**How**:
Added tests to prevent regression
**Checklist**:

Fix version_updated wrong exit code

---

troubadix/codespell/codespell.exclude

**What**:
To stay in sync with the codespell.exclude in the vts repo.
**Why**:
Parity PR for the changes done in greenbone/vulnerability-tests#547
**How**:
N/A
**Checklist**:

Change: Update codespell.exclude.

---

troubadix/plugins/badwords.py

**What**:
This PR adds an exception to the badwords plugin.
**Why**:
See pipeline of https://github.com/greenbone/vulnerability-tests/pull/561, because http://www.slackware.com/security/viewer.php?l=slackware-security&y=2009&m=slackware-security.603376 contains `openvasd`.
**How**:
**Checklist**:

Add: Exception to badwords plugin

---

troubadix/codespell/codespell.exclude

**What**:
To stay in sync with the codespell.exclude in the vts repo.
**Why**:
Parity PR for the changes done in greenbone/vulnerability-tests#572
**How**:
N/A
**Checklist**:

Change: Update codespell.exclude

---

tests/plugins/test_valid_script_tag_names.py
troubadix/plugins/valid_script_tag_names.py

**What**:
The plugin had missed to report a wrongly used script_tag() if it contained a newline because of an insufficient regex used in the custom written functions which got replaced by a helper function now.
- Closes: VTD-1667
- Part of: VTD-1616
**Why**:
The previous used functions in that plugin didn't took tags like e.g. the following below including newlines into account which caused false negatives in comparison to the old QA.
```
script_tag(name:"vuldetect", value:"Mylongdescriptionwitha
newline in between.");
```
**How**:
- :robot:
- Also ran `troubadix -d nasl/common/ --include-tests check_valid_script_tag_names -v` to check if no false positives are showing up
**Checklist**:

Fix valid_script_tag_names.py and add test cases.

---

troubadix/plugins/valid_script_tag_names.py

**What**:
- The description had missed the `- script_tag(name:"solution_type", value:"");` entry which was already checked in the plugin itself
- One comment was moved above the related part as it was a little bit misplaced below
- Some additional wording updates are also included
**Why**:
Consistency reasons.
**How**:
N/A
**Checklist**:

Documentation: Minor updates to the valid_script_tag_names function description

---

tests/plugins/test_spelling.py
troubadix/plugins/spelling.py

**What**:
Fixed duplicate output of spelling plugin
Jira: VTD-1668
**Why**:
After switching to `FilesPlugin` in #334 we had duplicated output
**How**:
**Checklist**:

Fix: Spelling plugin duplicate output

---

troubadix/codespell/codespell.exclude
troubadix/plugins/spelling.py

**What**:
From the newly added comment:
> Codespell has currently cna->can in the dictionary.txt which is causing false positives for CNA (widely used term in VTs) because codespell doesn't look at the casing. For now we're excluding any uppercase "CNA" results because these are usually false positives we don't want to report.
This now also allows to remove some bigger strings from the `codespell.exclude` afterwards.
**Why**:
Solve false positives like e.g. greenbone/vulnerability-tests#620 in a better way.
**How**:
N/A
**Checklist**:

Change: Exclude Codespell CNA false positives more generally.

---

tests/plugins/test_spelling.py
troubadix/plugins/spelling.py

**What**:
Spelling check would report 1 additional result with a trailing newline from codespell output.
**Why**:
Jira: VTD-1703
**How**:
**Checklist**:

Fix: Spelling check has too many results with trailing newline

---

tests/plugins/test_files/fail_permissions.nasl
tests/plugins/test_files/ok_permissions.nasl
tests/plugins/test_vt_file_permissions.py
troubadix/plugins/__init__.py
troubadix/plugins/vt_file_permission.py

**What**:
Adds a new plugin to check if VT files have the correct permissions (= not executable)
- Closes: Jira VTD-1680
- Part of: Jira VTD-1597
**Why**:
Long standing feature request that came up recently
**How**:
**Checklist**:

Add: VT Permissions Plugin

---

troubadix/plugins/spelling.py

**What**:
Parity PR for parts of greenbone/vulnerability-tests#829
**Why**:
Exclude false positives since the last codespell update from 2.1.0 to 2.2.0 yesterday.
**How**:
N/A
**Checklist**:

Change: Update codespell false positive exclusions in spelling plugin.

---

troubadix/plugins/script_family.py
troubadix/plugins/valid_oid.py

**What**:
As mentioned in a PR review of greenbone/notus-generator#440 there is no space in the product name as seen on e.g.:
- https://almalinux.org/
- https://en.wikipedia.org/wiki/AlmaLinux
which should be also reflected here.
**Why**:
Consistency reasons
**How**:
N/A
**Checklist**:

Fix: Product name of AlmaLinux in two plugins.

---

troubadix/standalone_plugins/changed_oid.py

**What**:
Changes the output stream for errors to `stderr` in the Changed-OID standalone plugin.
**Why**:
To make the behavior similar to `version-updated` and allow for output filtering in the QA wrapper in the VTS repo
**How**:
Test output below
**Checklist**:

Fix: Changed-OID output stream to stderr

---

troubadix/plugins/grammar.py

**What**:
N/A
- Should be merged after #377 so that we can make a new release including that afterwards
- Parity PR to greenbone/vulnerability-tests#1152
**Why**:
- The exclusion is required to allow passing the checks of greenbone/vulnerability-tests#1145
- The additional checks got added to catch things like `this files`
**How**:
N/A
**Checklist**:

Add: Additional grammar checks and exclusion

---

troubadix/plugins/grammar.py

**What**:
- Add an exclusion after #378
- Parity PR to greenbone/vulnerability-tests#1175
**Why**:
Exclude a few false positives
**How**:
N/A
**Checklist**:

Fix: Possible false positive in grammar plugin.

---

troubadix/plugins/grammar.py

Add: Additional grammar exclusion
Fix: Missing grammar exclusion which got dropped previously
**What**
- Some of the pattern should be checked case insensitive
- In 9c81e332f0941d5b9377119d1b9cacbe7d66eefb (from #381) one exclusion pattern seems to have been dropped accidentally
**Why**:
To solve the following false positives:
```
2022-09-14T21:00:17.9456275Z ℹ Checking pre2008/apache_slash.nasl (36913/98057)
2022-09-14T21:00:17.9471739Z ℹ     Results for plugin check_grammar
2022-09-14T21:00:17.9473703Z ×         VT/Include has the following grammar problem: # Description: Check for
2022-09-14T21:00:17.9475426Z            Apache Multiple '/' Vulnerability
2022-09-14T21:00:17.9476569Z           #
2022-09-14T21:00:17.9493818Z ℹ Checking …
```

Change: Use re.IGNORECASE for grammar exclusions

---

troubadix/plugins/grammar.py

**What**:
- See title
- Parity PR to greenbone/vulnerability-tests#1258
**Why**:
Previously to this change the following wasn't detected because the exclusion pattern `a few` matched against `a few CMS`:
```
ℹ Checking common/2018/phpunit/gb_phpunit_rce.nasl (39872/98072)
ℹ     Results for plugin check_grammar
×         VT/Include has the following grammar problem: # First fill the known location of a few CMS and CMS plugins shipping this files
```
**How**:
1. Ran Troubadix against the whole feed
2. Checked that no reports from the grammar plugin are reported
3. Updated the regex and re-ran Troubadix, now the grammar problem above is correctly reported while no additional false positives are happening
**Checklist**:

Change: Make one grammar exclusion pattern more strict.

---

troubadix/plugins/spelling.py

**What**:
See title
Notes:
- No new release required, there will be at least one follow-up PR for syncing the current `codespell.*` files from the vulerability-tests repo.
- Parity PR to greenbone/vulnerability-tests#1319
- Some further improvements for this plugin are not tracked in VTD-1773
**Why**:
Exclude a few false positives in a more generic way.
**How**:
Run the spelling plugin against the whole feed and less spelling issues should be reported.
**Checklist**:

Add: Additional exclusions to the spelling plugin.

---

tests/plugins/test_dependencies.py
troubadix/plugins/dependencies.py

**What**:
Fixes the false negatives when checking dependencies that are spread over multiple lines in `script_dependency` tags
**Why**:
Closes: VTD-1769
**How**:
**Checklist**:

Fix: Enable the dependency check to work on multiline entries

---

troubadix/plugins/spelling.py

**What**:
See title
**Why**:
Reduce false positives
**How**:
Before this PR:
```
$ troubadix -d nasl/common/ --include-tests check_spelling -v
ℹ Start linting 92893 files ... 
ℹ Run plugin check_spelling
ℹ     Results for plugin check_spelling
×         nasl/common/2017/opensuse/gb_opensuse_2017_1140_1.nasl:88: renderD ==> rendered
×         nasl/common/gsf/2022/f5/gb_f5_big_ip_K63771715.nasl:56: renderD ==> rendered
×         nasl/common/gb_hid_vertx_discoveryd_detect.nasl:4: VertX ==> vertex
×         nasl/common/gb_hid_vertx_discoveryd_detect.nasl:38: VertX ==> vertex
×         nasl/common/gb_hid_vertx_discoveryd_detect.nasl:40: VertX ==> vertex
×         nasl/common/gb_hid_vertx_discoveryd_detect.nasl:42: VertX ==> vertex
×         nasl/common/gb_hid_vertx_discoveryd_detect.nasl:112: …
```

Add: Additional spelling exclusions

---

troubadix/plugins/spelling.py

**What**:
The dot is part of a filename so it should be escaped.
**Why**:
N/A
**How**:
N/A
**Checklist**:

Fix: Missing escaping of a dot in a regex

---

tests/plugins/test_dependencies.py
troubadix/plugins/dependencies.py

**What**:
Fixes false positives in the dependency check if inline comments are present in the parameter list
**Why**:
Closes: VTD-1782
**How**:
Output before PR:
```
ℹ Start linting 131121 files ... 
ℹ Time elapsed: 0:00:10.588791
× check_dependencies                                      2      433
ℹ sum                                                     2      433
```
Output with PR:
```
ℹ Start linting 131121 files ... 
ℹ Time elapsed: 0:00:10.866805
⚠ …
```

Fix: Allow multiline dependencies with inline comments

---

tests/plugins/test_malformed_dependencies.py
troubadix/plugins/__init__.py
troubadix/plugins/malformed_dependencies.py

**What**:
Adds a plugin to check for dependencies which are malformed by being enumerated within a single pair of quotes.
**Why**:
Closes: VTD-444
**How**:
**Checklist**:

Add: Check for malformed script_dependency  values

---

tests/plugins/test_duplicate_oid.py
troubadix/plugins/duplicate_oid.py

**What**:
Before this PR:
```
ℹ Start linting 2 files ... 
ℹ Run plugin check_duplicate_oid
ℹ     Results for plugin check_duplicate_oid
×         OID 1.3.6.1.4.1.25623.1.0.95888 already used by 'common/compliance_tests.nasl'
ℹ Checking common/gsf/2009/opensuse/gb_suse_2008_056.nasl (1/2)
ℹ Checking common/compliance_tests.nasl (2/2)
ℹ Time elapsed: 0:00:00.018494
× check_duplicate_oid                                     1        0
ℹ sum                                                     1        0
```
after this PR:
```
ℹ Start linting 2 files ... 
ℹ Run plugin check_duplicate_oid
ℹ …
```

Change: Report both affected files in the Duplicated OID plugin.

---

troubadix/plugins/duplicate_oid.py

**What**:
The `KNOWN_DUPS` and `KNOWN_ABSENTS` dicts seems to be currently unused (probably some leftovers from previous development) so just dropping them.
**Why**:
Clean up / remove unused code.
**How**:
N/A
**Checklist**:

Remove: Unused dictionaries in Duplicate OID plugin.

---

troubadix/plugins/duplicate_oid.py

**What**:
- the use of `OPENVAS_OID_PREFIX` got dropped via #297 but the constant was left back. As it isn't used anymore it can be dropped
- the commented out import was probably a leftover from previous tests / development
- at some point in time we should consider to move `OID_RE` into `pattern.py` but for now this should be fine to keep it in the plugin itself
**Why**:
Clean up / remove unused code.
**How**:
N/A
**Checklist**:

Remove: Unused constant and commented out import statement in Duplicate OID plugin.

---

troubadix/codespell/codespell.exclude

**What**:
See title
Note: No new release required, could be included in some upcoming release.
**Why**:
Stay in sync with the vulnerability-tests repo (see e.g. greenbone/vulnerability-tests#2851)
**How**:
N/A
**Checklist**:

Change: Sync codespell.exclude with vulnerability-tests repo

---

troubadix/standalone_plugins/no_solution.py

**What**:
Shortens / deduplicates the output of reported VTs in the `no-solution` standalone by only printing the relative path instead of filename and relative path.
**Why**:
Closes: VTD-1895
**How**:
**Checklist**:

Change: Only print the relative path of a found VT

---

tests/plugins/test_solution_text.py
troubadix/plugins/solution_text.py

**What**:
- To allow something like e.g.:
```
script_tag(name:"solution", value:"No solution was made available by the vendor.
Vendor statement: The device in question doesn't support Crestron's security practices. We
recommend the HD-MD-4KZ alternative.");
```
- Blocking / first use in greenbone/vulnerability-tests#3178
**Why**:
Give VT-Devs more freedom in the solution text choice.
**How**:
:robot:
**Checklist**:

Add: Additional "WillNotFix" solution tag alternative for solution_text plugin.

---

troubadix/standalone_plugins/changed_oid.py
troubadix/standalone_plugins/version_updated.py

This PR fixes the formatting and a typo in the help text of `troubadix-changed-oid` and `troubadix-version-updated`.
To have the typo fixed and a space between the sentences.
Before:
```
-f FILES [FILES ...], --files FILES [FILES ...]
List of files to diff.If empty use all
files added or modifyed in the commit
range
```
After:
```
-f FILES [FILES ...], --files FILES [FILES ...]
List of files to diff. If empty use all
files added or modified in the commit
range.
```

Fix: Formatting and typo in help text

---

pyproject.toml
tests/standalone_plugins/changed_packages/__init__.py
tests/standalone_plugins/changed_packages/markers/__init__.py
tests/standalone_plugins/changed_packages/markers/test_added_epoch.py
tests/standalone_plugins/changed_packages/markers/test_added_release.py
tests/standalone_plugins/changed_packages/markers/test_added_udeb.py
tests/standalone_plugins/changed_packages/markers/test_changed_update.py
tests/standalone_plugins/changed_packages/markers/test_dropped_architecture.py
tests/standalone_plugins/changed_packages/test_changed_packages.py
tests/standalone_plugins/changed_packages/test_package.py
troubadix/standalone_plugins/changed_oid.py
troubadix/standalone_plugins/changed_packages/changed_packages.py
troubadix/standalone_plugins/changed_packages/marker/__init__.py
troubadix/standalone_plugins/changed_packages/marker/added_epoch.py
troubadix/standalone_plugins/changed_packages/marker/added_release.py
troubadix/standalone_plugins/changed_packages/marker/added_udeb.py
troubadix/standalone_plugins/changed_packages/marker/changed_update.py
troubadix/standalone_plugins/changed_packages/marker/dropped_architecture.py
troubadix/standalone_plugins/changed_packages/marker/marker.py
troubadix/standalone_plugins/changed_packages/package.py
troubadix/standalone_plugins/common.py
troubadix/standalone_plugins/version_updated.py

This PR adds `changed-packages` as a standalone plugin to Troubadix.
To give NASL developers to review large PRs easier and quickly check the changed packages.
VTA-397

Add: changed-packages standalone plugin 

---

pyproject.toml
tests/standalone_plugins/test_changed_cves.py
troubadix/helper/patterns.py
troubadix/standalone_plugins/changed_cves.py
troubadix/standalone_plugins/changed_packages/changed_packages.py
troubadix/standalone_plugins/common.py

This PR adds `changed-cves` as a standalone plugin to Troubadix.
To give NASL developers to review large PRs easier and quickly check the changed CVEs.
Example:
```
troubadix-changed-cves --files nasl/common/2015/debian/*                                             
ℹ Checking 308 file(s) from 4c338f222994e186320664d121198d14b78fc8bd to HEAD                                                                                                    
ℹ nasl/common/2015/debian/deb_3118.nasl has equal CVEs                                                                                                                          
⚠ CVEs for nasl/common/2015/debian/deb_3119.nasl differ …
```

Add: changed-cves standalone plugin

---

troubadix/argparser.py

This PR fixes Troubadix to fail when a system only has one core.
To not crash, because you cannot run with `1 // 2`, so `0` jobs.

Fix: Number of jobs must be 1 or higher

---

troubadix/plugins/spelling.py

- There is an issue when using `chardet` (internally used when `--hard-encoding-detection` is enabled) which got fixed recently via codespell-project/codespell#2785
- This PR disables the usage of `--hard-encoding-detection` until a new codespell containing the fix has been released
Current "full" runs of Troubadix against the whole feed are failing completely, this should make the runs pass again.
- VTD-1940
- codespell-project/codespell#2785

Change: Temporarily disable --hard-encoding-detection due to an issue in codespell 2.2.4

---

tests/plugins/test_copyright_year.py
troubadix/plugins/copyright_year.py

Note: No new release required, i will do a short follow-up PR with a minor unrelated improvement after this one got merged
Support the new copyright header like e.g.:
```
```
Closes: Jira VTD-1952

Extend copyright_year plugin.

---

tests/plugins/test_copyright_year.py
troubadix/plugins/copyright_year.py

Update the log message to include the `creation` word
Note: No dedicated release required, could be shipped with the next one.
Gives more context / background on the finding
None

Change: Update wording in copyright_year plugin. Adjust tests.

---

tests/plugins/test_security_messages.py
troubadix/plugins/security_messages.py

Changes the `security_message` plugin to check that either:
- A `severity` is present, as is a call to `security_message`
- A `severity` is absent, as is a call to `security_message`
Closes: VTD-1930

Change: security_message check to scan for security_message calls

---

tests/plugins/test_security_messages.py
troubadix/plugins/security_messages.py

This reverts #529 while creating a new version, so the faulty `deprecation` behavior will be reverted client side with a new release
Reopens: VTD-1930

Fix: Revert security_message check changes

---

troubadix/plugins/spelling.py

This PR generalizes the handling of misspelling in URLs by calling codespell with `--uri-ignore-words-list *`. This causes all misspellings in URLs and emails to be ignored.
To ignore misspellings in URLs.
I confirmed that this change doesn't degrade the behavior of the existing exclusions via
```
ℹ Start linting 659 files ... 
ℹ Time elapsed: 0:00:00.199386
ℹ sum                                                     0        0
```
I used `bsi.bund.de` in this example, because it has been previously excluded manually and I usually causes erroneous spelling errors:
``` …
```

Ignore misspellings in URLs

---

troubadix/plugins/spelling.py

This PR fixes https://github.com/greenbone/troubadix/pull/537 by correcting the syntax of arguments.
Currently, the `--uri-ignore-words-list` has no parameter, so it's no effective.
We could use either `"--uri-ignore-words-list", "*",` or `"--uri-ignore-words-list=*",` and I opted for the latter to align with the other arguments.
To actually make Codespell aware of the argument and parameter.

Fix: Codespell argument

---

troubadix/plugins/badwords.py

See title...
Notes:
- No dedicated release required, i will create another PR tomorrow
- Used in at least `template.nasl` and shouldn't be reported for that
Exclude false positives
N/A

Add: Exception to check_badwords plugin.

---

troubadix/plugins/copyright_year.py
troubadix/plugins/creation_date.py
troubadix/plugins/cve_format.py
troubadix/plugins/cvss_format.py
troubadix/plugins/dependencies.py
troubadix/plugins/dependency_category_order.py
troubadix/plugins/deprecated_dependency.py
troubadix/plugins/duplicate_oid.py
troubadix/plugins/duplicated_script_tags.py
troubadix/plugins/missing_desc_exit.py
troubadix/plugins/qod.py
troubadix/plugins/reporting_consistency.py
troubadix/plugins/script_calls_empty_values.py
troubadix/plugins/script_calls_recommended.py
troubadix/plugins/script_category.py
troubadix/plugins/script_copyright.py
troubadix/plugins/script_family.py
troubadix/plugins/script_tags_mandatory.py
troubadix/plugins/script_version_and_last_modification_tags.py
troubadix/plugins/solution_type.py
troubadix/plugins/using_display.py
troubadix/plugins/valid_oid.py
troubadix/standalone_plugins/version_updated.py

See title
To test run Troubadix with something like e.g. the following:
```
troubadix -vv --files template.nasl policy_control_template.nasl path/to/test_version_func_inc.nasl path/to/test_ipv6_packet_forgery.nasl
```
and see the false positives reports for these test / template files. Repeat it from this branch and against the VTs in the branch of the PR linked below and the false positives should be gone.
Notes:
- I have kept this a little bit "basic" on purpose because there are only three VTs / nasl files which currently needs to be excluded. If the exclusion for e.g. different keywords or similar are required we might want to handle this in a more advanced way in the future
- Using such "exclusion" keywords makes it easier to add additional testing files / templates without touching …

Change: Exclude template and testing VTs from some checks.

---

troubadix/standalone_plugins/version_updated.py

Just had noticed that the previously used `continue` was replaced by a `return` in #550 wrongly due to a copy'n'paste issue.
Fix a bug introduced in #550
None

Fix: Using a (wrong) return instead of the (correct) continue

---

.github/workflows/ci-python.yml

This PR prevents the deprecation warning ```Input 'version' has been deprecated with message: version input is deprecated. Please use `python-version` input instead.```.
After https://github.com/greenbone/actions/pull/552, the `version` input is deprecated and `python-version` should to be used instead.
The same as https://github.com/greenbone/notus-generator/pull/799.

Change: Use python-version instead of version

---

troubadix/plugins/spelling.py

See PR title
Exclude false positives for a subset of scripts
greenbone/vulnerability-tests#4583

Add: Spelling exemption folder for upcoming scripts containing German language

---

poetry.lock
pyproject.toml
troubadix/standalone_plugins/allowed_rev_diff.py

Adds a tool to troubadix that checks the diff between separate revs conforms to given patterns.
Required for the release branch
Part of: VTD-1666

Add: troubadix-allowed-rev-diff tool

---

troubadix/plugins/spelling.py

Reverts greenbone/troubadix#518
Now that [Codespell 2.2.5](https://github.com/codespell-project/codespell/releases/tag/v2.2.5) has been released which includes the fix from codespell-project/codespell#2785 we should revert the previous workaround from our side again and use the `chardet` option to detect the encoding.
Closes VTD-1940

Change: Revert "Change: Temporarily disable --hard-encoding-detection due to an issue in codespell 2.2.4"

---

tests/plugins/test_badwords.py
troubadix/plugins/badwords.py

See title...
Notes:
- Not sure how easily it could be done but maybe we could also change the  `DEFAULT_BADWORDS` list to a dict and allow an optional note / hint what to use instead? Some one else would need to take over though.
- Please make sure to review and merge all other current open PRs before doing a release for this change.
The reporting itself looks like e.g. the following now:
```
ℹ Checking common/gb_unknown_os_service_reporting.nasl (20152/90545)
ℹ     Results for plugin check_badwords
×         Badword in line    40:   the following NVTs:
Note/Hint: Please use the term "VT" instead.
```
Instead of `NVT` the term `VT` should be used nowadays
N/A

Change: Extend Badwords plugin with an additional term and test case.

---

troubadix/plugins/reporting_consistency.py

See title
Notes:
- Should be merged #589 so that that PR is included in the release after merging this PR here
- Maybe also merge possible "dependency updates" first which could arrive next week
So that we can add a `log_message() call to the updated VT from greenbone/vulnerability-tests#5829
None

Change: Add a valid VT to the ignore list of the reporting_consistency Plugin.

---

troubadix/plugins/qod.py

The new `package_unreliable` qod_type had been introduced via
- AP-1928
- SC-506
- greenbone/gsa#3353
- greenbone/gvmd#1782
- greenbone/ospd-openvas#605
in our software stack but wasn't added to Troubadix in the past.
Note: #590 should be merged first before merging this so that both are included in the new release
Allow the already implemented new qod_type in VTs.
N/A

Change: Add 'package_unreliable' to the allowed qod_type values.

---

troubadix/plugins/badwords.py

Both strings doesn't exist in the feed anymore (due to some license header updating works) and the exceptions can be removed accordingly.
Note: We might want to merge this before #595 so that both are included in the same release.
Less code and more strict checks due to less exceptions.
None

Change: Remove a few "Badwords" exceptions not required anymore.

---

poetry.lock
pyproject.toml
tests/plugins/test_encoding.py
troubadix/plugins/encoding.py

This PR improves encoding detection by using charset-normalizer instead of chardet.
For example, chardet detects `geprüft` as ISO-8859-9:
```
>>> b'\x67\x65\x70\x72\xfc\x66\x74'.decode("latin_1")
'geprüft'
>>> chardet.detect(b'\x67\x65\x70\x72\xfc\x66\x74')
{'encoding': 'ISO-8859-9', 'confidence': 0.7300222957397617, 'language': 'Turkish'}
```
While this is technically correct, `geprüft` is also valid ISO-8859-1.
My first approach was to manually detect the encodings by calling e.g. `.decode("latin_1")` on the NASL content to check, if the content can be decoded with ASCII or Latin-1. If it can't (like UTF-8), it's an invalid encoding. This however turned out to be not as reliable as expected.
I therefore switched to charset-normalizer and pass our only two allowed encodings.
```
>>> …
```

Improve encoding detection

---

tests/plugins/test_badwords.py
troubadix/plugins/badwords.py

- As of today there won't be any VTs having `# OpenVAS Vulnerability Test` and includes having `# OpenVAS Include File` in the header anymore
- Parity PR for:
- greenbone/vulnerability-tests#6383
- greenbone/vulnerability-tests#6412
No dedicated release required, i will create another PR later this week after which we can do a new release
More strict checks and less code
N/A

Change: Remove now unnecessary exclusions in badwords plugin.

---

.github/workflows/ci-python.yml
.pylintrc
README.md
poetry.lock
pyproject.toml
tests/plugins/test_cve_format.py
troubadix/plugins/spelling.py

This PR bumps the minimum required Python version to 3.9 or higher and updates this projects dependencies.
- The bump to Python 3.9+ is required because
- The latest Greenbone autohooks require Python 3.8+
- The latest `pontos` requires Python 3.9+
- Not having the latest version of them also causes their dependencies to be outdated and not updatable
- Dependabot is still failing for multiple dependencies (see https://github.com/dependabot/dependabot-core/issues/7389): 
```
updater | Dependabot encountered '21' error(s) during execution, please check the logs for more details.
updater | +------------------------------------+
updater | |   Dependencies failed to update    |
updater | +--------------------+---------------+
updater | | isort              | unknown_error |
updater | | rich …
```

Require Python 3.9+ and update dependencies

---

troubadix/plugins/badwords.py

This PR adds a badword exclude.
`technocrackers` is the author of https://de.wordpress.org/plugins/woo-bulk-price-update/ and not a bad word.

Add: Badword exclude

---

poetry.lock
pyproject.toml

This PR downgrades `validators` to 0.20.0 after a version bump to a buggy version via #594.
To get rid off false positives. I checked every version, starting from the latest (0.22.0) and 0.20.0 was the first one with no false positives.
This can be revered as soon as https://github.com/python-validators/validators/issues/296 is solved.
I ran the Troubadix against the affected NASL script and confirmed that there no longer is a false positive reported.

Change: Downgrade validators to 0.20.0

---

.github/dependabot.yml

Pontos introduced a new `Deps` conventional commit message type with greenbone/pontos#771 / DEVOPS-669 which will be put into a new `Dependencies` section in the generated changelog.
Current example dependabot config from Pontos (The `scope` seen in the PR above was removed again via greenbone/pontos#776) can be seen at e.g.:
https://github.com/greenbone/pontos/blob/main/.github/dependabot.yml
and the "outcome" here:
https://github.com/greenbone/pontos/releases/tag/v23.9.0
- To prevent empty releases with an empty Changelog like seen in e.g. https://github.com/greenbone/troubadix/releases/tag/v23.9.1
- Furthermore dependency updates might affect a specific release (e.g. if some issues got fixed in a dependency update or similar) and should be included in the Changelog
Related to:
- …

Change: Update dependabot.yml to prefix commits with Deps

---

.github/workflows/conventional-commits.yml
changelog.toml

- Update conventional-commits.yml to work with bot PRs
- Use default config for conventional commits
Use the same code / content as in e.g. https://github.com/greenbone/pontos/blob/main/.github/workflows/conventional-commits.yml which includes the updates from:
- greenbone/pontos#822
- greenbone/pontos#785
and also do the same as greenbone/pontos#793 to use the default config for conventional commits.
#616 is now prefixing all Dependabot PRs with `Deps:` to have them included in the changelog. But it seems the conventional-commits workflow wasn't able do identify these (probably because it wasn't able to get the data / info from the PR) and  thus only reported a `No conventional commits found.` like seen here:
https://github.com/greenbone/troubadix/pull/618#issuecomment-1718023674
while …

Change: Various updates for the conventional commits handling

---

tests/plugins/test_script_xref_url.py

Adds the valid URLs which i have identified / collected previously in:
https://github.com/python-validators/validators/issues/296#issuecomment-1708338654
To catch issues caused by dependency updates earlier (like happened via #594 and reverted afterwards via #609). This is important especially as we only had a very basic URL `http://www.example.com` in the current test.
None directly

Change: Add additional valid URLs to script_xref() URL test.

---

troubadix/plugins/spelling.py

See title...
Prevent false positives for German text parts like e.g.:
> IT-Grundschutz M4.147: Sichere Nutzung von EFS unter Windows (Windows)
None

Change: Add additional spelling exclusion

---

troubadix/plugins/badwords.py

See title
Fix a false positive
- greenbone/vulnerability-tests#7301
- https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/IPXRXD5VXBZHBGMUM77B52CJJMG7EJGI

Add: Add exclusion to Badword plugin.

---

tests/plugins/test_script_calls_empty_values.py
tests/plugins/test_script_tag_whitespaces.py
tests/plugins/test_script_xref_form.py
troubadix/helper/patterns.py
troubadix/plugins/script_tag_whitespaces.py
troubadix/plugins/script_xref_form.py

Note: #643 should be merged first to have it included in the next release as well
Extending the plugin accordingly to catch something like below seen in greenbone/vulnerability-tests#7373
```
script_xref(name:"Policy", value:"CIS Microsoft Windows 10 Enterprise (Release 22H2) Benchmark v2.0.0: REMOVE - 2.3.17 (L1) Ensure 'User Account Control: Allow UIAccess applications to prompt for elevation without using the secure desktop' is set to 'Disabled' Ticket #8863 ");
```
Old QA step was able to catch this while the new Troubadix not because it seems there was no support for checking `script_xref()` tags within it.
While doing this i had also noticed that there were two `_XREF_TAG_PATTERN` defined and `get_xref_pattern` didn't worked as expected for the `script_tag_whitespaces.py` plugins so …

Change: Various script_xref() related extensions / modifications.

---

tests/plugins/test_trailing_spaces_tabs.py
troubadix/plugins/trailing_spaces_tabs.py

This PR enhances the check for trailing spaces and tabs to show the line number.
Currently, a developer only gets notified _that_ there is an issue, but not _where_. This is annoying.
It also corrects (I couldn't imagine why this would be wanted) the behavior that only the first / a single error is reported instead of all.
Before
```
➜  troubadix git:(main) poetry run troubadix --file ../vulnerability-tests/nasl/common/gather-package-list.nasl -v
ℹ Checking common/gather-package-list.nasl (1/1)
ℹ     Results for plugin check_todo_tbd
⚠         VT contains #TODO/TBD/@todo keywords.
ℹ     Results for plugin check_trailing_spaces_tabs
×         The VT has one or more trailing spaces and/or tabs!
ℹ Time elapsed: 0:00:04.096467
Plugin …
```

Show line number in check of trailing spaces / tabs

---

tests/plugins/test_script_version_and_last_modification_tags.py
troubadix/plugins/script_version_and_last_modification_tags.py

Use the datetime module to parse and validate the retrieved last modification date. Added checks for general structure, containing only single date, weekday matching the date.
The last modification date is only checked for correct length, not for syntax and values.
[VTOPS-128](https://jira.greenbone.net/browse/VTOPS-128)

Add: Extend date verification for last modification tag

---

troubadix/plugins/http_links_in_tags.py

This PR adds an exclude for the http_links_in_tags check.
Because https://github.com/greenbone/vulnerability-tests/actions/runs/8342778895/job/22831672387?pr=10122 is failing, e.g. for https://alas.aws.amazon.com/AL2/ALAS-2023-2110.html.
Noticed during https://github.com/greenbone/vulnerability-tests/pull/10122.

Add: Exclude for http_links_in_tags check

---

.github/workflows/ci-python.yml

This PR fixes Codecov in our workflow.
To have Codecov working again.
For whatever reason we already have `secrets.CODECOV_TOKEN` present, but we're not using it.
This kind of error has been first introduced in https://github.com/greenbone/troubadix/pull/668, but can't really tell why. Also, the error got shadowed by another one, because in the CI runs prior to that one it also failed due to a different error.

Fix: Codecov in workflow

---

tests/plugins/test_overlong_description_lines.py

This was newly introduced in / via #681 in 2024 but the wrong 2022 copyright year probably has been copied over from another one.
Obvious...
Related to: VTOPS-174

Fix: Fix wrong Copyright year for new tests file.

---

tests/plugins/test_overlong_description_lines.py
troubadix/plugins/overlong_description_lines.py

See title
Similar to the existing `script_name()` and `script_xref()` we can't have newlines in the name and/or value tag of `script_add_preference()` and should not do any any reporting for now.
None specific

Change: Add script_add_preference() as exclusion to overlong line plugin.

---

troubadix/plugins/http_links_in_tags.py

This PR adds an exclusion to the http_links_in_tags check.
To avoid a false-positive.
Fixes https://github.com/greenbone/vulnerability-tests/pull/10815#issuecomment-2099813010.

Add: Exclusion to http_links_in_tags

---

tests/plugins/test_valid_oid.py
troubadix/plugins/valid_oid.py

This PR fixes the spelling of `Red Hat`.
Because we use the correct spelling `Red Hat` instead of `RedHat` in the upcoming VTs. Troubadix will fail otherwise.

Fix: Red Hat spelling

---

troubadix/codespell/codespell.exclude

Added all the new entries from the productive codespell.exclude to the local codespell-exclude.
This was created due to failing checks in greenbone/vulnerability-tests#11392 but it seems it is not really needed. Nevertheless, it is best to keep the two files in sync from time to time.
None

Change: Update codespell exclusion.

---

troubadix/plugins/badwords.py
troubadix/plugins/todo_tbd.py

`gb_gsa_detect.nasl` will be renamed to `gb_greenbone_gsa_http_detect.nasl` for consistency reasons in the PR below so we need to adjust / extend the file name exclusions here.
Required for: greenbone/vulnerability-tests#11394
None

Change: Add additional exclusion file name in two plugins.

---

pyproject.toml
tests/standalone_plugins/test_deprecate_vts.py
troubadix/standalone_plugins/deprecate_vts.py

Add a standalone plugin to deprecate VTs. The script takes either a single file or a directory of files, and writes the updated file to a new location.
The changes the script should accomplish are (from the relevant internal Confluence page):
1) add a note to the summary of why the VT is deprecated
2) remove all code after the description block
3) add the early exit (66) to the end
4) add the deprecated=True tag
5) remove unneeded script tags
For the Red Hat deployment we need to deprecate hundreds of VTs. Therefore it makes sense to have a script that does this
VTA-531

Add: standalone plugin for deprecating VTs

---

tests/plugins/test_overlong_description_lines.py
troubadix/plugins/overlong_description_lines.py

Add an exclusion similar to #716 for the new plugin from #712
Prevents the reporting of something which won't be changed anytime soon.
None

Change: Extend the exclusion of overlong description lines. Adjust test.

---

tests/plugins/test_vt_placement.py

Syntax of such tags is:
```
script_tag(name:"foo", value:"bar");
```
and not:
```
script_tag(name:"foo", value="bar");
```
Obvious...
None

Fix: Usage of a wrong NASL syntax in one test.

---

README.md

This PR updates the installation instructions by stealing them from the pontos README.
Because `python3 -m pip install..` is no longer recommended and broken in current Ubuntu releases.

Update installation instrucations in README

---

troubadix/plugins/reporting_consistency.py

See title
Required for greenbone/vulnerability-tests#13423
None

Change: Rename exclusion string after change in the relevant file name.

---

troubadix/standalone_plugins/version_updated.py

See title
Required for greenbone/vulnerability-tests#13527
None

Change: Add exclusion to one standalone plugin.

---

tests/plugins/test_script_xref_url.py
troubadix/plugins/script_xref_url.py

- Adds more cases which should be detected which seems to be not covered by the validators package (yet)
- Excludes a few additional valid / allowed URLs which are now reported as invalid after the version bump of the validators package in #763
- To catch additional possible malformed URLs introduced by e.g. some automatic extraction or by copy'n'paste like seen / noticed in:
- greenbone/vulnerability-tests#13985
- greenbone/vulnerability-tests#13986
- greenbone/vulnerability-tests#13953
- greenbone/vulnerability-tests#13959
- greenbone/vulnerability-tests#14055
- To exclude a few special URLs which seems to be valid but edge cases and reported as invalid by the validators package
None

Change: Extend invalid URL plugin and relevant tests.

---

tests/standalone_plugins/test_deprecate_vts.py
troubadix/standalone_plugins/deprecate_vts.py

The plugin had created a coding style like e.g.:
```
script_tag(name:"deprecated", value:TRUE);
exit(0);
}
exit(66);
```
and had missed to indent the `exit(0);` by two spaces. This is fixed now.
Have correct coding style / indentation in the NASL code
greenbone/vulnerability-tests#15425 (Fixing all existing VTs which had that missing indentation originating from the previous version of this plugin)

Change: Fix NASL coding style output of deprecate VT plugin. Adjust test.

---

tests/plugins/test_overlong_description_lines.py
troubadix/plugins/overlong_description_lines.py

See title
Note: No new release required, can be shipped / included in one of the next once more changes have happened to Troubadix.
Prevents some reporting similar to the `script_xref()` case for URLs we shouldn't break
None

Change: Extend ignore list of overlong description lines plugin. Adjust tests.

---

troubadix/plugins/script_family.py

This PR adds the openSUSE Local Security Checks family
Because Notus is using a dedicated script family.
Jira: VTA-660
Ran this against the NASL scripts with the new family

Add: openSUSE Local Security Checks family

---

tests/plugins/test_creation_date.py
troubadix/plugins/creation_date.py

This PR adds a check to the creation date check to check whether the `creation_date` is smaller than / equal `last_modification`
Because a VT cannot be modified before it has been created.
Jira: VTOPS-210
Depends on: greenbone/vulnerability-tests#16642

Add: Check for creation date <= last modification date

---

tests/test_runner.py
troubadix/plugins/__init__.py

This PR changes the behavior of Troubadix when included or excluded plugins are not found. Troubadix will now name which plugins are unknown and - if possible - suggest which plugin could be meant instead.
Before:
```
➜  troubadix git:(main) poetry run troubadix --file ~/Greenbone/vulnerability-tests/nasl/common/gather-package-list.nasl --include-test check_spelling grammer foo check_newlines
ℹ Time elapsed: 0:00:00.198147
ℹ sum
```
After:
```
➜  troubadix git:(vtops-127_suggestion_on_unknown_plugin) poetry run troubadix --file …
```

Add: Complain about unknown plugins and suggest fix

---

troubadix/plugins/valid_oid.py

- See title
- As the OID range `50000` through `179999` is now assigned we can use a single check for these
- OID range `119NNN` got assigned recently and needs to be allowed
- Required for: greenbone/vulnerability-tests#18251
None

Change: Update/extend valid OID ranges.

---

troubadix/plugins/http_links_in_tags.py

See title
Note: Should be merged after #846 so that both are included in a new release.
To prevent false positives seen here:
- greenbone/vulnerability-tests#20278
- greenbone/vulnerability-tests#20285
N/A

Change: Add exclusion to HTTP link check plugin.

---

tests/plugins/test_badwords.py
troubadix/plugins/badwords.py

Notes:
- We should generally exclude `http://` and `https://` URLs as these are immutable and shouldn't be changed / require separate exclusions for each
- No dedicated release required IMHO, can be shipped with the next release
Initially wanted to include this URL in greenbone/vulnerability-tests#20688 but the check failed.
None

Change: Generally exclude URLs (http/https) in Badword plugin.

---

tests/plugins/test_dependencies.py
troubadix/plugins/valid_oid.py

- Drop or replace "enterprise" folder as only "gsf" is currently used
- Use `+` to join a string instead of implicit string concatenation
Notes:
- It seems it was planned in the past to use `/enterprise` for a folder but this was never put into production. So just let us use the current `/gsf`
- No dedicated release required, this can be shipped with the next one
- This also solves the following two CodeQL suggestions:
- https://github.com/greenbone/troubadix/security/code-scanning/17
- https://github.com/greenbone/troubadix/security/code-scanning/16
Reflect reality and solves two additional CodeQL suggestions as a bonus.
None

Change: Various valid OID plugin and dependencies tests updates.
