- naslinter/plugins/qod.py
- tests/plugins/test_qod.py
- tests/plugins/test_script_version_and_last_modification_tags.py
- troubadix/plugins/qod.py
**What**:
Contains check for QoD existence and validation
DEVOPS-130
**Why**:
**How**:
**Checklist**:
> Add: qod validation

- tests/test_runner.py
- troubadix/plugins/__init__.py
- troubadix/runner.py
**What**:
Fail if no plugin is run.
**Why**:
This is very likely an error on the users side for example a typo in the
include parameter.
**How**:
**Checklist**:
> Raise exception if no plugin is run

- troubadix/runner.py
**What**:
Handle keyboard interrupt gracefully
**Why**:
Avoid long and useless tracebacks if a user pressed CTRL+C during the
run of troubadix to abort it.
**How**:
**Checklist**:
> Handle keyboard interrupt gracefully

- troubadix/runner.py
**What**:
Allow to debug which plugins are to be run
**Why**:
Because the user input may contain typos it might be interesting for
debugging purposes which plugins are actually run.
**How**:
**Checklist**:
> Allow to debug which plugins are to be run

- tests/test_runner.py
- troubadix/runner.py
**What**:
Change console output to list results of a plugin
**Why**:
Actually the plugin has been run already. We just collected and
displayed the results.
**How**:
**Checklist**:
> Change console output to list results of a plugin

- tests/plugins/test_cvss_format.py
- troubadix/plugins/cvss_format.py
**What**:
Added check for CVE without cvss value
**Why**:
This was missing so far-
**How**:
test
**Checklist**:
> Check CVE without CVSS

- tests/test_runner.py
- troubadix/runner.py
- troubadix/troubadix.py
**What**: Add really simple exit code handling
**Why**:
**How**:
**Checklist**:
> Add really simple exit code handling.

- tests/plugins/test_description.py
- troubadix/plugins/description.py
**What**: Let the description check find everything.
**Why**:
To be on the safe side, since script_description
does not exist anymore.
**How**:
**Checklist**:
> Let the description check find everything

- troubadix/plugins/copyright_year.py
**What**:
**Why**:
**How**:
**Checklist**:
> Change: Only run `copyright_year` on `.nasl` files

- README.md
**What**:
Removed reference to openvas in README.md
**Why**:
Was ovelooked in https://github.com/greenbone/troubadix/pull/125
**How**:
**Checklist**:
> Remove: Reference to openvas lint removed

- troubadix/runner.py
**What**: Basic error and warning count
**Why**:
**How**:
**Checklist**:
> Init error count

- tests/plugins/test_cve_format.py
- troubadix/plugins/cve_format.py
**What**:
**Why**:
**How**:
**Checklist**:
> Change: Missing CVE is only a Warning, not an Error.

- troubadix/codespell/codespell.exclude
Pulls the current version from our productive repository.
> Change: Sync codespell.exclude with current version

- tests/plugins/test_log_messages.py
- troubadix/plugins/log_messages.py
**What**: Use warning if log_messags and security_messages exist in nasl file
**Why**:
https://jira.greenbone.net/browse/DEVOPS-183
**How**:
**Checklist**:
> Use warning if log_messags and security_messages exist in nasl file

- tests/plugins/test_newlines.py
- tests/plugins/test_tabs.py
- troubadix/plugins/newlines.py
- troubadix/plugins/tabs.py
**What**: Remove replacement in "check_tabs" and "newlines" steps
and replace warnings with errors.
**Why**:
https://jira.greenbone.net/browse/DEVOPS-184
**How**:
**Checklist**:
> Remove replacement in "check_tabs" and "newlines" steps

- tests/plugins/test_overlong_script_tags.py
- troubadix/helper/patterns.py
- troubadix/plugins/overlong_script_tags.py
**What**:
CheckOverlongScriptTags add line break support and set the limit to 3000
**Why**:
https://jira.greenbone.net/browse/DEVOPS-189
**How**:
**Checklist**:
> CheckOverlongScriptTags add line break support and set the limit to 3000

- troubadix/plugins/using_display.py
**What**: Exclude enterprise/dicom.inc
**Why**:
https://jira.greenbone.net/browse/DEVOPS-191
**How**:
**Checklist**:
> Exclude enterprise/dicom.inc

- troubadix/plugins/forking_nasl_funcs.py
**What**: Exclude *.inc files from forking_nasl_funcs
**Why**:
https://jira.greenbone.net/browse/DEVOPS-192
**How**:
**Checklist**:
> Exclude *.inc files

- troubadix/plugins/security_messages.py
**What**: Exclude *.inc files from security_messages
**Why**:
https://jira.greenbone.net/browse/DEVOPS-194
**How**:
**Checklist**:
> Exclude *.inc files from security_messages

- tests/plugins/test_badwords.py
- troubadix/plugins/badwords.py
**What**:
Updated exceptions and implemented check for file-specific exceptions 
**Why**:
Produced false positive
**How**:
**Checklist**:
> Fix: fixed badword plugin

- troubadix/plugins/reporting_consistency.py
**What**: Fix false positives in check_reporting_consistency
**Why**:
DEVOPS-179
**How**:
**Checklist**:
> Fix false positives in check_reporting_consistency

- troubadix/plugins/double_end_points.py
**What**:
The VT in question has been updated recently and this comment is no longer valid / required.
**Why**:
**How**:
**Checklist**:
> Change: Remove outdated comment.

- tests/plugins/test_badwords.py
- tests/plugins/test_copyright_text.py
- tests/plugins/test_duplicated_oid.py
- tests/plugins/test_encoding.py
- tests/plugins/test_files/nasl/21.04/runner/test_valid_oid.nasl
- tests/plugins/test_illegal_characters.py
- tests/plugins/test_newlines.py
- tests/plugins/test_update_modification_date.py
- tests/test_argparser.py
- tests/test_runner.py
- troubadix/argparser.py
- troubadix/helper/__init__.py
- troubadix/plugin.py
- troubadix/plugins/__init__.py
- troubadix/plugins/copyright_text.py
- troubadix/plugins/dependency_category_order.py
- troubadix/plugins/deprecated_dependency.py
- troubadix/plugins/duplicate_oid.py
- troubadix/plugins/illegal_characters.py
- troubadix/plugins/update_modification_date.py
- troubadix/runner.py
- troubadix/troubadix.py
**What**:
* Don't hardcode encoding
* Unify result reporting
* Remove obsolete code
* Improve Plugins handling
* Some cleanup
* Remove unused arguments from troubadix
**Why**:
**How**:
**Checklist**:
> Improvements

- troubadix/codespell/codespell.exclude
- troubadix/plugins/grammar.py
**What**:
Applies some recent changes done to the productive vts repo.
**Why**:
**How**:
**Checklist**:
> Change: Update codespell and grammar exclusions.

- tests/plugins/test_files/fail_bad_new_line.nasl
- tests/plugins/test_newlines.py
- troubadix/plugins/newlines.py
**What**: Fix check for wrong newlines and renewed check for whitespaces
**Why**:
The test for new lines was broken because python text read changes all newline characters to /n.
The test for spaces was previously misunderstood by me.
**How**:
**Checklist**:
> Fix check for wrong newlines and renewed check for whitespaces

- troubadix/codespell/codespell.exclude
- troubadix/plugins/grammar.py
- troubadix/plugins/http_links_in_tags.py
**What**:
Applies some recent changes done to the productive vts repo.
**Why**:
**How**:
**Checklist**:
> Change: Update codespell, grammar and http link in tag exclusions.

- tests/plugins/test_files/nasl/21.04/fail_solution_template.nasl
- tests/plugins/test_no_solution.py
- tests/test_runner.py
- troubadix/plugins/__init__.py
- troubadix/plugins/no_solution.py
**What**:
Added plugin to evaluate missing solutions within solution tag in collaboration with @pascalholthaus 
**Why**:
FE-173
**How**:
**Checklist**:
> Add: Plugin for handling of missing solutions added

- tests/plugins/test_no_solution.py
- troubadix/plugins/no_solution.py
**What**:
Exclude .inc files print and check datetime convert errors
**Why**:
**How**:
**Checklist**:
> Exclude .inc files print and check datetime convert errors

- tests/plugins/__init__.py
- tests/plugins/test_dependencies.py
- tests/test_helper.py
- troubadix/helper/helper.py
- troubadix/plugins/dependencies.py
**What**:
Improve dependencies check and make it independent of the gsf and enterprise folders.
**Why**:
Hardcoded folders are a pain to maintain.
**How**:
**Checklist**:
> Update checking dependencies

- troubadix/helper/helper.py
- troubadix/plugins/vt_placement.py
**What**:
**Why**:
**How**:
**Checklist**:
> Small improvement for abstracting the enterprise folders

- troubadix/runner.py
**What**:
Differentiate between errors and warnings properly
**Why**:
DEVOPS-195
**How**:
**Checklist**:
> Change: Improve results summary output

- .github/workflows/ci-python.yml
**What**: Remove ospd-openvas image from ci-python.yml workflow
**Why**:
There is no longer a plugin that it requires
**How**:
**Checklist**:
> Remove ospd-openvas image from ci-python.yml workflow

- troubadix/plugins/valid_oid.py
**What**:
Added OID ranges for 2 new Members from Altimi
**Checklist**:
> Added OID ranges for new altimi members

- tests/test_runner.py
- troubadix/runner.py
**What**:
**Why**:
It should display for example file 1/1 instead of 0/1.
**How**:
**Checklist**:
> Fix displaying counting the current file

- troubadix/plugins/__init__.py
**What**:
**Why**:
**How**:
**Checklist**:
> Add: Load missing illegal characters plugin

- tests/test_runner.py
- troubadix/runner.py
- troubadix/troubadix.py
**What**:
**Why**:
Make the return value more logical (aka. pythonic) and don't use C logic
where False (== 0) is the value for "nothing did go wrong".
**How**:
**Checklist**:
> Change: Return True from Runner.run if the run has been successful

- tests/plugins/test_copyright_text.py
- tests/plugins/test_copyright_year.py
- tests/plugins/test_update_modification_date.py
- tests/test_argparser.py
- tests/test_runner.py
- troubadix/argparser.py
- troubadix/plugin.py
- troubadix/plugins/copyright_text.py
- troubadix/plugins/copyright_year.py
- troubadix/plugins/illegal_characters.py
- troubadix/plugins/update_modification_date.py
- troubadix/runner.py
- troubadix/troubadix.py
**What**:
Introduce an explicit fix phase for plugins and a `--fix` CLI argument to run this phase.
https://jira.greenbone.net/browse/DEVOPS-208
**Why**:
Separate checks and fixing content. This is how other formatters and linters are working.
**How**:
**Checklist**:
> Add --fix argument

- troubadix/codespell/codespell.exclude
- troubadix/plugins/forking_nasl_funcs.py
**What**:
Applies some recent changes done to the productive vts repo.
**Why**:
**How**:
**Checklist**:
> Change: Update codespell and forking NASL funcs exclusions.

- troubadix/codespell/codespell.exclude
**What**:
Added update instructions to the file header
**Why**:
As discussed with CFi, to keep this process transparent and easy to use.
**Checklist**:
> Codespell exclude instructions

- tests/plugins/test_forking_nasl_functions.py
- troubadix/plugins/__init__.py
- troubadix/plugins/forking_nasl_functions.py
**What**:
Don't use abbreviations. We have IDEs with code completion.
**Why**:
**How**:
**Checklist**:
> Rename forking nasl function module and class

- tests/test_reporter.py
- tests/test_runner.py
- troubadix/reporter.py
- troubadix/results.py
- troubadix/runner.py
- troubadix/troubadix.py
**What**:
* Splitting the `Runner` and the reporting functions
**Why**:
* There were quite a lot of functions in the `Runner` that did not fit into a class called like this, thus I introduced a `Reporter` class, doing all Output stuff
**How**:
**Checklist**:
> Change: Move reporting from `Runner` into separate `Reporter` class

- tests/plugins/test_http_links_in_tags.py
- tests/plugins/test_valid_oid.py
- troubadix/codespell/codespell.exclude
- troubadix/plugins/http_links_in_tags.py
- troubadix/plugins/valid_oid.py
**What**:
Additions and changes to multiple checks for Slackware launch.
**Why**:
To keep parity between old QA and Troubadix
**Checklist**:
> Updates for Slackware launch

- .github/workflows/ci-python.yml
- pyproject.toml
**What**:
Run tests and linting on Python 3.10 too.
**Why**:
**How**:
**Checklist**:
> Enable support for Python 3.10

- troubadix/codespell/codespell.exclude
**What**:
Updated with the recent changes done in the productive repository.
**Why**:
N/A
**How**:
N/A
**Checklist**:
> Change: Update codespell exclusions.

- tests/plugins/test_http_links_in_tags.py
- troubadix/plugins/http_links_in_tags.py
**What**:
Updated with the recent changes done in the productive repository.
**Why**:
N/A
**How**:
N/A
**Checklist**:
> Change: Additions to http_links_in_tags exclusions.

- tests/plugins/test_files/nasl/21.04/fail_solution_template.nasl
- tests/plugins/test_files/nasl/21.04/test.inc
- tests/plugins/test_no_solution.py
- tests/test_naslinter.py
- troubadix/plugins/cve_format.py
- troubadix/plugins/no_solution.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix: Do not run `noSolution` on VTs with a severity of `0.0`.

- .github/dependabot.yml
**What**: Enabling Dependabot version updates for actions
**Why**:
**How**:
**Checklist**:
> Enabling Dependabot version updates for actions

- tests/plugins/test_files/nasl/21.04/fail_solution_template.nasl
- tests/plugins/test_no_solution.py
- troubadix/plugins/no_solution.py
**What**:Only check "NoneAvailable" qod_type VTs in no_solution.py
**Why**:
**How**:
**Checklist**:
> Only check "NoneAvailable" qod_type VTs in no_solution.py

- tests/plugins/test_copyright_year.py
- troubadix/plugins/copyright_year.py
…te`.
**What**:
**Why**:
* removing ~1500 unclear false-positives
**How**:
**Checklist**:
> Change: Add exception for the `pre2008` VTs with unknown `creation_date`.

- tests/plugins/test_grammar.py
- troubadix/plugins/grammar.py
**What**: Use finditer on the full content
**Why**:
Line by line may not find everything.
**How**:
**Checklist**:
> Update check_grammar: Use finditer on the full content

- troubadix/plugins/overlong_script_tags.py
**What**: Exclude inc files where they are not needed.
**Why**:
**How**:
**Checklist**:
> Exclude inc files

- troubadix/plugins/badwords.py
**What**:Add new allowed badwords
**Why**:
**How**:
**Checklist**:
> Update badwords.py: Add new allowed badwords

- troubadix/plugins/spelling.py
**What**:
Import of spellcheck main function to save time compared to subprocess call.
Tested it with a lot of spelling errors in the nasl/common directory.
Should work.
**Why**:
**How**:
**Checklist**:
> Direct import of spellcheck main

- tests/test_argparser.py
- tests/test_reporter.py
- tests/test_runner.py
- troubadix/argparser.py
- troubadix/reporter.py
- troubadix/troubadix.py
**What**:
Add --ignore-warnings to statistic and add an extra logfile for the statistic.
**Why**:
**How**:
**Checklist**:
> Add --ignore-warnings to statistic and add an extra logfile for the statistic

- troubadix/plugins/dependencies.py
**What**: Move +d+.nasl file check on first place in dependencies.py
**Why**:
**How**:
**Checklist**:
> Move +d+.nasl file check on first place

- troubadix/plugins/misplaced_compare_in_if.py
**What**:
Just to avoid a QA failure for VTs which can't be changed currently and which was accepted like this.
Making a release in #266 had failed for me for unknown reasons so it would be great that a @greenbone/devops member could do a release after this merge.
**Why**:
Those are files which have this misplaced compare since their very first version. As changing the if now might change their behavior and the VTs are candidates for deprecation they are ignored for now.
**How**:
This is mostly copied from `overlong_script_tags.py` and no special test was done. If unit tests or similar are required please take over as i'm not familiar with that topic and currently can't effort the time to dig into it.
**Checklist**:
> Change: Add excluded files to misplaced_compare_in_if.py plugin.

- tests/plugins/test_misplaced_compare_in_if.py
**What**:
Add additional test cases similar to #268 which are basically a copy of the existing ones with some different variants of ok / not ok strings.
**Why**:
More test cases
**How**:
N/A
**Checklist**:
> Add: Additional ok and nok test cases for test_misplaced_compare_in_if.py

- troubadix/argparser.py
- troubadix/troubadix.py
**What**:
* Add a flag to print the troubadix version
**Why**:
* Easy check what version you run.
**How**:
**Checklist**:
> Add: Version command to troubadix

- tests/plugins/test_dependencies.py
- troubadix/plugins/dependencies.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix: False Positives in the dependencies check

- tests/plugins/test_spelling.py
- troubadix/plugins/spelling.py
**What**:
Support local codespell files.
**Why**:
**How**:
**Checklist**:
> Support local codespell files

- troubadix/plugins/trailing_spaces_tabs.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix: Trailing whitespace check

- troubadix/plugins/__init__.py
- troubadix/plugins/script_tag_whitespaces.py
**What**:
**Why**:
**How**:
**Checklist**:
> Fix: Import and fix Check for trailing, leading whitespaces in script_tag values

- troubadix/helper/helper.py
- troubadix/plugins/dependencies.py
- troubadix/plugins/vt_placement.py
**What**: Add common, 21.04, 22.04 folder to search path in vt_placement.py and move the 
FEED_VERSIONS list to the helper module.
**Why**:
**How**:
**Checklist**:
> Add common, 21.04, 22.04 folder to search path in vt_placement.py

- troubadix/standalone_plugins/changed_oid.py
**What**:
Use latin-1 encoding not utf-8 ,git diff output uses raw bytes.
**Why**:
Git diff output uses raw bytes
**How**:
**Checklist**:
> Fix: use latin-1 encoding not utf-8 ,git diff output uses raw bytes.

- troubadix/plugins/__init__.py
**What**: Enable missing plugins
**Why**:
**How**:
**Checklist**:
> Fix: Enable missing plugins

- troubadix/helper/patterns.py
- troubadix/plugins/script_calls_mandatory.py
**What**:
Fix: script_calls_mandatory report right call name and fix SpecialScriptTag.VERSION pattern for variables.
**Why**:
**How**:
**Checklist**:
> Fix: script_calls_mandatory report right call name

- troubadix/troubadix.py
**What**:
Fix: --from-file and --files, auto remove duplicate files
**Why**:
**How**:
**Checklist**:
> Fix: --from-file and --files, auto remove duplicate files

- troubadix/plugins/dependency_category_order.py
- troubadix/plugins/deprecated_dependency.py
**What**:Fix root folder check in dependency_category_order and deprecated_dependency and fix: +d+.nasl file dependency detection.
**Why**:
**How**:
**Checklist**:
> Fix: root folder check in dependency_category_order and deprecated_dependency.

- tests/test_helper.py
- troubadix/helper/helper.py
**What**:
Allow passing a relative path for root directory
**Why**:
Don't crash if a relative directory is passed as root.
**How**:
**Checklist**:
> Fix: Allow passing a relative path for root directory

- poetry.lock
- pyproject.toml
- tests/test_argparser.py
- tests/test_naslinter.py
- tests/test_reporter.py
- tests/test_runner.py
- troubadix/argparser.py
- troubadix/reporter.py
- troubadix/troubadix.py
**What**:
Fix pontos terminal usage
[DEVOPS-296](https://jira.greenbone.net/browse/DEVOPS-296)
**Why**:
Pontos 22.7.0 broke the terminal API
**How**:
**Checklist**:
> Fix pontos terminal usage

- troubadix/plugins/script_xref_url.py
**What**:
Add URL allow list for urls not recognized by the validators api.
If anyone has a better solution let me know.
**Why**:
Some urls are not recognized by the validators api.
**How**:
**Checklist**:
> Add: URL allow list for urls not recognized by the validators api

- troubadix/helper/patterns.py
**What**:
**Why**:
DEVOPS-292
**How**:
**Checklist**:
> Refactor: documentation

- troubadix/helper/patterns.py
- troubadix/plugins/reporting_consistency.py
**What**:
Found via:
```
$ codespell . -e -S ".git,codespell.*"
```
Note: Some "false positives" are showing up.
**Why**:
N/A
**How**:
N/A
**Checklist**:
> Fix: Typos

- troubadix/codespell/codespell.exclude
- troubadix/plugins/spelling.py
**What**:
Parity PR for:
- greenbone/vulnerability-tests#436
- greenbone/vulnerability-tests#426
**Why**:
Just to remove a few entries from codespell.exclude and move the exclusion to the similar SLES one for consistency reasons.
**How**:
N/A
**Checklist**:
> Change: Update spelling exclusion and codespell.exclude.

- poetry.lock
- pyproject.toml
**What**:
Update dependencies to latest versions
**Why**:
Check if CI is failing too
**How**:
**Checklist**:
> Update dependencies to latest versions

- troubadix/codespell/codespell.exclude
**What**:
N/A
**Why**:
Parity PR for greenbone/vulnerability-tests#614
**How**:
N/A
**Checklist**:
> Change: Update codespell.exclude

- troubadix/plugins/grammar.py
**What**:
Check a few additional things like `This flaws` which is quite common.
**Why**:
N/A
**How**:
N/A
**Checklist**:
> Add: Additional grammar checks to the grammar plugin.

- troubadix/plugins/grammar.py
**What**:
Short follow-up to #353 to exclude one valid sentence.
**Why**:
N/A
**How**:
N/A
**Checklist**:
> Add: Additional valid sentence to the grammar exclusion.

- troubadix/plugins/script_family.py
- troubadix/plugins/valid_oid.py
**What**:
Adds the script family for Alma Linux and the OID pattern used by Notus-Generator
**Why**:
Part of: VTD-1310
**How**:
**Checklist**:
> Add Alma Linux script family and OID

- tests/plugins/test_illegal_characters.py
- troubadix/plugins/illegal_characters.py
**What**:
Reworked the illegal characters check so that it distinguishes between forbidden characters and characters that only should create a warning
**Why**:
The previous behavior from #53 only created warnings, even if the file content was illegal.
**How**:
**Checklist**:
> Reworked illegal characters check

- troubadix/codespell/codespell.exclude
- troubadix/plugins/spelling.py
**What**:
Parity PR for greenbone/vulnerability-tests#978 to make that PR to pass the QA.
**Why**:
Exclude false positives.
**How**:
N/A
**Checklist**:
> Change: Update codespell.exclude and spelling exclusion in spelling plugin.

- troubadix/plugins/grammar.py
**What**:
This PRs adds a grammar exclusion
**Why**:
To except cases like in https://ubuntu.com/security/notices/USN-4711-1.
**How**:
**Checklist**:
> Add: grammar exclusion

- troubadix/plugins/grammar.py
**What**:
- See title
- Parity PR to greenbone/vulnerability-tests#1201
**Why**:
Less lines and repetitive code
**How**:
N/A
**Checklist**:
> Change: Use list / loop behavior for grammar exclusions. Minor exclusion updates / additions.

- troubadix/plugins/grammar.py
**What**:
This PR fixes the broken grammar check, introduced in https://github.com/greenbone/troubadix/pull/381/files.
This causes e.g. https://github.com/greenbone/vulnerability-tests/pull/1206 to fail.
**Why**:
To make it work again. With the current implementation the loop always returns during the first run.
**How**:
Current main:
```
(.venv) ➜  troubadix git:(main) poetry run troubadix --files ../vulnerability-tests/nasl/common/2021/ubuntu/gb_ubuntu_USN_4713_2.nasl -v
ℹ Checking common/2021/ubuntu/gb_ubuntu_USN_4713_2.nasl (1/1)
ℹ     Results for plugin check_grammar
×         VT/Include has the following grammar problem: requests. An attacker with access to at least
one LUN in a multiple
ℹ Time elapsed: 0:00:00.408078
Plugin …
```
> Fix: Broken grammar check

- tests/plugins/test_grammar.py
**What**:
Adds a test to check correct false positive behavior in the grammar check
**Why**:
To verify behavior of #382 
**How**:
**Checklist**:
> Add: Test for correctly detected fps in grammar check

- tests/helper/test_linguistic_exception_handler.py
- troubadix/helper/linguistic_exception_handler.py
- troubadix/plugins/spelling.py
**What**:
Adds a generic mechanism to filter false positives in grammar and spelling detections.
`spelling.py` is reworked according to the new mechanism.
**Why**:
Part of: VTD-1773
**How**:
**Checklist**:
> Linguistic exception mechanism & spelling rework

- troubadix/codespell/codespell.exclude
- troubadix/codespell/codespell.ignore
- troubadix/plugins/spelling.py
**What**:
- Ignore "unsecure" correction in a more generic way
- Sync codespell.* files with vulnerability-tests repo
Parity PR to greenbone/vulnerability-tests#1463
**Why**:
Reduce false positives
**How**:
N/A
**Checklist**:
> Various codespell / spelling correction updates

- .gitignore
**What**:
Utility additions in gitignore
**Why**:
**How**:
**Checklist**:
> Gitignore utility

- troubadix/standalone_plugins/no_solution.py
**What**:
Fixes a type error when passing a value for the `-m` parameter
**Why**:
Parameter produced an error
**How**:
**Checklist**:
> Fix typing issue with --milestones parameter

- tests/plugins/test_encoding.py
- troubadix/plugins/encoding.py
**What**:
Overhauls the encoding check to catch possible errors more broadly.
**Why**:
Closes: VTD-1854
**How**:
**Checklist**:
> Overhaul encoding check

- troubadix/plugins/encoding.py
**What**:
Fixes problems with detecting wrong encodings on attic files.
**Why**:
Fixes: VTD-1854
**How**:
**Checklist**:
> Fix: Roman encoding problem

- troubadix/standalone_plugins/no_solution.py
**What**:
Adds an exit code that returns wether VTs have been found to report (0 = none, 1 = found)
**Why**:
Part of: VTD-1871
**How**:
**Checklist**:
> Change: Add exit code to determinate wether VTs to report were found

- troubadix/standalone_plugins/no_solution.py
**What**:
`troubadix-no-solution` now catches internal errors and just displays the error message
**Why**:
Closes: VTD-1896
**How**:
**Checklist**:
> Fix crashing behavior

- troubadix/standalone_plugins/no_solution.py
**What**:
Changes reporting so that reported VTs are displayed ordered to their relative path
**Why**:
Closes: VTD-1904
**How**:
**Checklist**:
> Order reported VTs

- tests/plugins/test_grammar.py
- troubadix/plugins/grammar.py
1. To catch things like (missing `s` in `requests`):
```
Sends multiple HTTP GET request and checks the responses.
```
2. Also did some additional minor improvements / extensions related to similar checks
3. No new release required yet (have noticed some additional updates which i would like to submit separately)
N/A
N/A
> Add: Additional grammar checks and related tests.

- troubadix/plugins/grammar.py
Note: No new dedicated release required, can be shipped with the next one
To prevent a few false positives.
N/A
> Add: Additional grammar exclusions

- troubadix/plugins/grammar.py
- troubadix/plugins/spelling.py
Note: No new dedicated release required, can be shipped with the next one
To prevent a few false positives.
N/A
> Add: Additional spelling and grammar exclusions.

- tests/plugins/test_security_messages.py
- troubadix/plugins/security_messages.py
Reintroduces the fixed changes from #529 
Closes: VTD-1930
> Change: Reintroduce security_message absence / presence detection

- tests/plugins/test_deprecated_functions.py
- troubadix/plugins/deprecated_functions.py
- Use re.MULTILINE as some functions might span over multiple lines
- Minor text / reporting updates
- Make the checks a little bit more strict to avoid possible false positives
- Add additional tests
Note: No dedicated release required
N/A
N/A
> Change: Various CheckDeprecatedFunctions plugin updates / improvements.

- tests/plugins/test_script_tag_whitespaces.py
- troubadix/plugins/script_tag_whitespaces.py
- Extends the existing plugins with the capability to detect something like e.g.:
```
script_name("MyProduct Multiple Vulnerabilities ");
```
- Added / updated tests accordingly
Catch more cases which should be prevented to be submitted in VTs.
- greenbone/vulnerability-tests#4778 (for an example PR fixing such found VTs)
> Change: Extend newlines/spaces plugin with script_name() support.

- troubadix/plugins/prod_svc_detect_in_vulnvt.py
N/A
Note: No dedicated release required, can be shipped with the next one.
Quoting from the added comment:
> VTD-1173 is a tracking ticket to update this so we don't need to report it on each run. Especially as:
> - this VT is a quite aged one and currently not problematic
> - the plugin should only prevent to introduce new VTs using this approach
None
> Change: Exclude one existing VT from being reported unnecessarily.

- troubadix/codespell/codespell.exclude
- troubadix/plugins/badwords.py
See title
More / better reporting
None
> Change: Update pattern and/or exclusions in badwords and codespell files.

- troubadix/codespell/codespell.exclude
Sync the exclusions with the productive repository
Note: Should be merged before #588 so that this is included in the next release together with that PR
N/A
N/A
> Change: Update codespell exclusion.

- tests/standalone_plugins/test_no_solution.py
- troubadix/standalone_plugins/no_solution.py
Changes to `no-solution` tool to work like in the old QA
Do not merge until given the OK
Part of: VTOPS-62
Enables: #9269 in VTS
> Change: Update no-solution algorithm

- troubadix/plugins/http_links_in_tags.py
Add a new exclusion as seen in this failure: https://github.com/greenbone/vulnerability-tests/actions/runs/9027164163/job/24805610906?pr=10857
https://github.com/greenbone/vulnerability-tests/pull/10857
> Add: Exclusion to http_links_in_tags

- troubadix/plugins/valid_oid.py
Adds a oid range that was given to Raphael.
> Change: add a additional oid range

- troubadix/codespell/codespell.additions
- troubadix/codespell/codespell.exclude
- troubadix/codespell/codespell.ignore
See title
Note: No new release required, can be shipped with one of the next ones.
Stay in sync with the productive repo
None
> Change: Update codespell files.

- troubadix/plugins/grammar.py
See title
Required for: greenbone/vulnerability-tests#16871
N/A
> Change: Add exclusion pattern to Grammar plugin.

- tests/plugins/test_grammar.py
- troubadix/plugins/grammar.py
See title
Note: #813 should be merged first so that this PR is included in the release after merging this one here.
Catch more copy'n'paste mistakes.
- greenbone/vulnerability-tests#17621
- greenbone/vulnerability-tests#17622
> Change: Update grammar regex pattern and extend relevant tests.

- tests/plugins/test_copyright_text.py
- troubadix/plugins/script_xref_url.py
Note: No dedicated release required, this can be shipped with the next one
Solving the remaining open CodeQL suggestions about this topic.
None
> Change: Use `+` to join a string instead of implicit string concatenation.
